### ISSUE TITLE
Pelipper Horse Replacer

### ISSUE THREAD

**Issue by kananrubys** [StardewModders/Modding-Ideas#53]
As the title says, I want a mod that replaces the horse with Pelipper from Pokemon.
I'm sure it's Mystery Dungeon: Explorers of Sky sprites would work well and wouldn't be too hard to mod in.

**Comment by Entoarox** [comment]
Please split the harvest moon replacer into its own suggestion, having multiple suggestions in the same place would make it difficult for people to accept them.

**Comment by HopeWasHere** [comment]
I'm currently working on a huge mod that makes it so every Pokemon can be used for any animal. I'm about done with the small animals (baby chicks, dinosaurs, rabbits, etc) for Kanto, but I could side track and make the Pelliper one no problem.

**Comment by kananrubys** [comment]
Awesome, thanks!

**Comment by kananrubys** [comment]
Will I need to change the name of the .xnb to horse.xnb for it to work?

**Comment by HopeWasHere** [comment]
Yeah, sorry. Forgot to change it...

**Comment by kananrubys** [comment]
![image](https://user-images.githubusercontent.com/32626144/31410408-84c464b6-addc-11e7-897c-91421016af97.png)
for some reason the front of the face looks odd when riding it

**Comment by HopeWasHere** [comment]
I think I know the problem, one minute

**Comment by HopeWasHere** [comment]
[Pelipper.zip](https://github.com/StardewModders/Modding-Ideas/files/1373437/Pelipper.zip)
Try that one, let me know if that works

**Comment by kananrubys** [comment]
![image](https://user-images.githubusercontent.com/32626144/31410930-0c8d6eb4-adde-11e7-94bc-392a9429cbe6.png)
still looks weird

**Comment by HopeWasHere** [comment]
I think it's because of the default size of the horse head is more narrow than Pelipper's head it might not work...

**Comment by kananrubys** [comment]
Aww man,, anything else you can replace with Pelipper? I just want my boy in the game in some way.

**Comment by HopeWasHere** [comment]
I'm sure I could make him a larger animal (cow, sheep, etc) because he fits just fine in the 32x32 space. It's just how the players body interacts with the horse, the head is meant to go on a certain way to bock part of the player's body. The only way I could see to get the horse to work would be to add the pelipper head to the farmer sprite sheet, and even that might not work...

**Comment by kananrubys** [comment]
Ahh I see, can you make him a sheep then?

**Comment by HopeWasHere** [comment]
Finished, sorry it took me so long...

It will work for any of the following, you just have to name it the right thing:
- Baby Brown Cow
- Brown Cow
- Baby White Cow
- White Cow
- Baby Goat
- Goat
- Baby Sheep
- Sheep
- Baby Pig
- Pig

When doing the sheep, you must have a Sheep.xnb file and a SheeredSheep.xnb file. Since there isn't a "sheered" version of Pelipper, if you want it to be the sheep you can have the one file work for both the sheered and non-sheered.
[Pelipper Large Animal.zip](https://github.com/StardewModders/Modding-Ideas/files/1377458/Pelipper.Large.Animal.zip)

**Comment by Entoarox** [comment]
As this request has been completed, I am closing this issue and marking it complete.
