### ISSUE TITLE
Junimo Hut Range

### ISSUE THREAD

**Issue by Library-Tech** [StardewModders/Modding-Ideas#67]
There are mods out there that show the range of sprinklers and scarecrows so you can place them to cover the most ground ... I can't find any that do the same for the junimo hut. Could one be made to show the range covered by the hut as you place it? (i.e. an overlay grid showing how far the junimos will collect crops)

**Comment by danvolchek** [comment]
Hey @Library-Tech, I'm the creator of the sprinkler + scarecrow range mod (it's got bee houses now too :)). I forgot about Junimo Huts - I'll add this in the next version, which should come out soonish!

**Comment by BlatantDecoy** [comment]
UI Info Suite does this, as well as sprinkler, scarecrow and beehive ranges

**Comment by Pathoschild** [comment]
[Data Maps](https://www.nexusmods.com/stardewvalley/mods/1691) is another option — it shows Junimo hut, sprinkler, scarecrow, and bee house coverage (including support for custom sprinklers like Better Sprinklers and Cobalt). Data Maps shows the range when placing the building, too.

Since there's a few mods that do this already, I'll mark it done.
