### ISSUE TITLE
Choose your own land titles

### ISSUE THREAD

**Issue by HopeWasHere** [StardewModders/Modding-Ideas#88]
Suggestion from Reddit: https://www.reddit.com/r/StardewValley/comments/7voz8r/you_should_be_able_to_choose_between_farm_and/

Player gets choice on if there land is called a farm or a ranch (possibly more titles).

Bonus:
The name based on your output similar to how leader titles change in Civ V based on which policy tree you unlock

Farm, Orchard, Ranch, Winery, etc.

**Comment by Warilized** [comment]
So like, if I name it "Greenhill Ranch" at the creation screen, instead of the games interpreting my input as "Greenhill Ranch Farm", it instead replace the default word/title "Farm" as "Ranch" and resulting in the name as "Greenhill Ranch"?

I think it will be difficult because as far as i know, character dialogues is separate from the system's...
You can replace system string to match what farm name type you give, but any other character will always mention Farm except if you go each string and whenever they mention Farm, you replace it manually...

But maybe a mod where if you choose "Ranch" as your title, every string that mention "Farm"(default) will be replaced with any title you choose (of course if this is feasible)...

Also, instead naming your farm "Greenhill Ranch" to make "Farm" get replaced by "Ranch", it's more user friendly if it's a dropdown option instead.

Having the option to change titles in mid-game is wonderful too tho.

**Comment by thingwithwings** [comment]
Would it be possible/easier to just eliminate the 'farm' part from the game calling it "[insert name] Farm" and then you can name it anything you want, including ranch, orchard, winery, or nothing at all?

**Comment by mopquill** [comment]
I've made a mod that lets you rename the suffix. It defaults to ranch, you can set it with a command, it remembers what you set it to per-save. Available for download [here](https://www.nexusmods.com/stardewvalley/mods/2200).
